port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "HY2-Server-Client"
    type: socks5
    server: 45.152.66.230      # 服务端 HY2 客户端的 IP
    port: 1080
    udp: true
    skip-cert-verify: true

proxy-groups:
  - name: "Auto"
    type: select
    proxies:
      - "HY2-Server-Client"

rules:
  - GEOIP,CN,DIRECT
  - DOMAIN-SUFFIX,google.com,Auto
  - DOMAIN-KEYWORD,youtube,Auto
  - MATCH,Auto

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  fallback:
    - 8.8.4.4
    - 1.0.0.1