port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "HY2-Local"
    type: socks5
    server: 127.0.0.1
    port: 1080
    udp: true

proxy-groups:
  - name: "Auto"
    type: select
    proxies:
      - "HY2-Local"

rules:
  - MATCH,Auto
